const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',

  EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
};
export default UserActionTypes;
